import { defineAsyncComponent, type Component } from "vue"
import { type BlockType } from "../types"

// @ts-ignore - these are virtual files generated by Nuxt
import { BLOCK_RENDERER_COMPONENT_MAP } from "#rimelight-internal/block-renderer-map"
// @ts-ignore
import { BLOCK_EDITOR_COMPONENT_MAP } from "#rimelight-internal/block-editor-map"

export const getBlockRendererComponent = (
    type: BlockType | string
): Component | undefined => {
  const loader = BLOCK_RENDERER_COMPONENT_MAP[type]

  if (!loader) {
    console.warn(`[BlockMapper] No renderer found for type: ${type}`)
    return undefined
  }

  return defineAsyncComponent(loader)
}

export const getBlockEditorComponent = (
    type: BlockType | string
): Component | undefined => {
  const loader = BLOCK_EDITOR_COMPONENT_MAP[type]

  if (!loader) {
    console.warn(`[EditorBlockMapper] No editor found for type: ${type}`)
    return undefined
  }

  return defineAsyncComponent(loader)
}