import {
  defineNuxtModule,
  addComponentsDir,
  addImportsDir,
  addTemplate,
  createResolver
} from "@nuxt/kit"
import { name, version, homepage } from "../package.json"
import { defaultOptions } from "./defaults"

import { readdirSync } from "node:fs"
import { basename } from "node:path"

interface CalloutOptions {
  icon: string
  title: string
  tooltip: string
}

export interface ModuleOptions {
  /**
   * Prefix for components
   * @defaultValue `RC`
   */
  prefix?: string
  callouts: {
    info: CalloutOptions
    success: CalloutOptions
    warning: CalloutOptions
    error: CalloutOptions
    commentary: CalloutOptions
    ideation: CalloutOptions
    source: CalloutOptions
  }
}

export default defineNuxtModule<ModuleOptions>({
  meta: {
    name,
    version,
    docs: homepage,
    configKey: "rimelightComponents",
    compatibility: {
      nuxt: ">=4.0.0"
    }
  },
  defaults: defaultOptions,
  hooks: {},
  moduleDependencies: {
    "@nuxt/image": {
      version: ">=1.0.0",
      optional: false,
      overrides: {},
      defaults: {}
    },
    "@nuxtjs/i18n": {
      version: ">=10.1.1",
      optional: false,
      overrides: {},
      defaults: {}
    },
    "@nuxt/ui": {
      version: ">=4.0.0",
      optional: false,
      overrides: {},
      defaults: {
        prefix: "U",
        theme: {
          colors: [
            "neutral",
            "primary",
            "secondary",
            "info",
            "success",
            "warning",
            "error",
            "commentary",
            "ideation",
            "source"
          ]
        }
      }
    },
    "@vueuse/nuxt": {
      version: ">=13.9.0",
      optional: false,
      overrides: {},
      defaults: {}
    },
    "motion-v/nuxt": {
      version: ">=1.7.2",
      optional: false,
      overrides: {},
      defaults: {}
    }
  },
  setup(options, nuxt) {
    const resolver = createResolver(import.meta.url)

    nuxt.options.appConfig.rimelightComponents = options

    addComponentsDir({
      path: resolver.resolve("./runtime/components/"),
      pathPrefix: false,
      prefix: options.prefix,
      global: true
    })

    addImportsDir(resolver.resolve("./runtime/composables"))
    addImportsDir(resolver.resolve("./runtime/types"))
    addImportsDir(resolver.resolve("./runtime/utils"))

    const blocksPath = resolver.resolve("./runtime/components/blocks")

    // Scan the directory for all .vue files
    const blockFiles = readdirSync(blocksPath).filter((name) =>
      name.endsWith(".vue")
    )

    // Generate a clean list of component names (e.g., ['ParagraphBlock', 'ImageBlock'])
    const blockNames = blockFiles.map((file) => basename(file, ".vue"))

    // --- 2. Generate the Component Map Template ---
    // Create the content of the file we want to generate at .nuxt/rimelight-blocks-map.mjs
    const template = addTemplate({
      filename: "rimelight-blocks-map.mjs",
      getContents: () => {
        let content = "export const BLOCK_COMPONENT_MAP = {\n"

        blockNames.forEach((name) => {
          // 💡 CRITICAL CHANGE: Use the module's alias and the 'runtime' path.
          // The Nuxt module builder is responsible for mapping 'rimelight-components/runtime'
          // to the correct source or stubbed directory in dev mode.
          const componentPath = `rimelight-components/runtime/components/blocks/${name}.vue`

          // Use a special prefix for the import to signal Nuxt/Vite to use the alias
          content += `  '${name}': () => import('${componentPath}'),\n`
        })

        content += "}\n"
        return content
      },
      write: true
    })

    addTemplate({
      filename: "rimelight-blocks-map.d.ts",
      getContents: () => {
        // Define the type for the dynamic import functions
        const componentImporterType =
          '() => Promise<{ default: import("vue").Component }>'

        let content = `// Generated by rimelight-components Nuxt Module\n`
        content += `import { Component } from 'vue'\n`
        content += `export declare const BLOCK_COMPONENT_MAP: { [key: string]: ${componentImporterType} | undefined }\n`

        // Add specific type hints for each block for better IDE completion
        blockNames.forEach((name) => {
          content += `export declare const ${name}: ${componentImporterType}\n`
        })

        return content
      },
      write: true
    })

    // --- 3. Expose the map template to the runtime via an alias ---
    // This allows blockMapper.ts to import the map using '#build/rimelight-blocks-map'
    nuxt.options.alias["#build/rimelight-blocks-map"] = template.dst
  },
  onInstall() {
    console.log("Setting up rimelight-components for the first time!")
  },
  onUpgrade() {
    console.log("Upgrading rimelight-components.")
  }
})
