import { addTemplate } from "@nuxt/kit"

/**
 * Generates and adds the component map templates (JS and DTS) to the Nuxt build.
 *
 * @param blockNames An array of component names (e.g., ['ParagraphBlock', 'ImageBlock']).
 */
export function addBlockMapTemplates(blockNames: string[]) {
  // Generate the Component Map Template
  const template = addTemplate({
    filename: "rimelight-blocks-map.mjs",
    getContents: () => {
      let content = "export const BLOCK_RENDERER_COMPONENT_MAP = {\n"

      blockNames.forEach((name) => {
        const fullComponentName = `${name}Renderer` // e.g., 'SectionBlockRenderer'
        const componentPath = `rimelight-components/components/blocks/renderer/${fullComponentName}.vue`

        // The dynamic import function
        content += `  '${name}': () => import('${componentPath}'),\n`
      })

      content += "}\n"
      return content
    },
    write: true
  })

  // Generate the Component Map Template
  addTemplate({
    filename: "rimelight-blocks-map.d.ts",
    getContents: () => {
      // Define the type for the dynamic import functions
      const componentImporterType =
        '() => Promise<{ default: import("vue").Component }>'

      let content = `// Generated by rimelight-components Nuxt Module\n`
      content += `import { Component } from 'vue'\n`
      content += `export declare const BLOCK_RENDERER_COMPONENT_MAP: { [key: string]: ${componentImporterType} | undefined }\n`

      // Add specific type hints for each block for better IDE completion
      blockNames.forEach((name) => {
        content += `export declare const ${name}: ${componentImporterType}\n`
      })

      return content
    },
    write: true
  })

  // Return the main template object so its destination path (`template.dst`) can be aliased.
  return template
}

/**
 * Generates and adds the component map templates (JS and DTS) specifically for
 * Editor Blocks to the Nuxt build.
 *
 * @param blockNames An array of Editor Block component names (e.g., ['EditorParagraphBlock', 'EditorImageBlock']).
 */
export function addEditorBlockMapTemplates(blockNames: string[]) {
  // Define the type for the dynamic import functions
  // Explicitly defining this once helps with reusability and clarity.
  const componentImporterType =
    '() => Promise<{ default: import("vue").Component }>'

  // 1. Generate the Component Map Template (MJS)
  const template = addTemplate({
    filename: "rimelight-editor-blocks-map.mjs",
    getContents: () => {
      let content = "export const BLOCK_EDITOR_COMPONENT_MAP = {\n"

      blockNames.forEach((name) => {
        const fullComponentName = `${name}Editor` // e.g., 'SectionBlockEditor'
        const componentPath = `rimelight-components/components/blocks/editor/${fullComponentName}.vue`

        // The dynamic import function
        content += `  '${name}': () => import('${componentPath}'),\n`
      })

      content += "}\n"
      return content
    },
    write: true
  })

  // 2. Generate the Component Map Template (DTS)
  addTemplate({
    filename: "rimelight-editor-blocks-map.d.ts",
    getContents: () => {
      let content = `// Generated by rimelight-components Nuxt Module\n`
      content += `import { Component } from 'vue'\n`
      // **Updated map name in the declaration**
      content += `export declare const BLOCK_EDITOR_COMPONENT_MAP: { [key: string]: ${componentImporterType} | undefined }\n`

      // Add specific type hints for each block for better IDE completion
      blockNames.forEach((name) => {
        content += `export declare const ${name}: ${componentImporterType}\n`
      })

      return content
    },
    write: true
  })

  // Return the main template object so its destination path (`template.dst`) can be aliased.
  return template
}
