import { addTemplate } from "@nuxt/kit"
import type { Resolver } from "@nuxt/kit"

/**
 * Generates and adds the component map templates (JS and DTS) to the Nuxt build.
 *
 * @param blockNames An array of component names (e.g., ['ParagraphBlock', 'ImageBlock']).
 * @param resolver The module's resolver from createResolver(import.meta.url).
 */
export function addBlockMapTemplates(blockNames: string[]) {
  // Generate the Component Map Template
  const template = addTemplate({
    filename: "rimelight-blocks-map.mjs",
    getContents: () => {
      let content = "export const BLOCK_COMPONENT_MAP = {\n"

      blockNames.forEach((name) => {
        // Use the module's alias and the 'runtime' path for dynamic import.
        const componentPath = `rimelight-components/components/blocks/${name}.vue`

        // The dynamic import function
        content += `  '${name}': () => import('${componentPath}'),\n`
      })

      content += "}\n"
      return content
    },
    write: true
  })

  // Generate the Component Map Template
  addTemplate({
    filename: "rimelight-blocks-map.d.ts",
    getContents: () => {
      // Define the type for the dynamic import functions
      const componentImporterType =
        '() => Promise<{ default: import("vue").Component }>'

      let content = `// Generated by rimelight-components Nuxt Module\n`
      content += `import { Component } from 'vue'\n`
      content += `export declare const BLOCK_COMPONENT_MAP: { [key: string]: ${componentImporterType} | undefined }\n`

      // Add specific type hints for each block for better IDE completion
      blockNames.forEach((name) => {
        content += `export declare const ${name}: ${componentImporterType}\n`
      })

      return content
    },
    write: true
  })

  // Return the main template object so its destination path (`template.dst`) can be aliased.
  return template
}
