import { addTemplate } from "@nuxt/kit"

export function addBlockMapTemplates(blockNames: string[]) {
  const template = addTemplate({
    filename: "rimelight-block-renderer-map.mjs",
    getContents: () => {
      let content = "export const BLOCK_RENDERER_COMPONENT_MAP = {\n"
      blockNames.forEach((name) => {
        // Map the key to the component name string
        content += `  '${name}': '${name}Renderer',\n`
      })
      content += "}\n"
      return content
    },
    write: true
  })

  addTemplate({
    filename: "rimelight-block-renderer-map.d.ts",
    getContents: () => {
      let content = `// Generated by rimelight-components\n`
      content += `export declare const BLOCK_RENDERER_COMPONENT_MAP: Record<string, string>\n`
      return content
    },
    write: true
  })

  return template
}

export function addEditorBlockMapTemplates(blockNames: string[]) {
  const template = addTemplate({
    filename: "rimelight-block-editor-map.mjs",
    getContents: () => {
      let content = "export const BLOCK_EDITOR_COMPONENT_MAP = {\n"
      blockNames.forEach((name) => {
        content += `  '${name}': '${name}Editor',\n`
      })
      content += "}\n"
      return content
    },
    write: true
  })

  addTemplate({
    filename: "rimelight-block-editor-map.d.ts",
    getContents: () => {
      let content = `// Generated by rimelight-components\n`
      content += `export declare const BLOCK_EDITOR_COMPONENT_MAP: Record<string, string>\n`
      return content
    },
    write: true
  })

  return template
}